services:
  db:
    image: mysql:8.0.34
    restart: always
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
    env_file: ./.env
    environment:
      - MYSQL_DATABASE=$DB
      - MYSQL_ROOT_PASSWORD=$DB_ROOT_PASSWORD
      - MYSQL_PASSWORD=$DB_PASSWORD
      - MYSQL_USER=$DB_USER
    ports:
      - 3307:$DB_PORT
    networks:
      - this-api-net
    volumes:
      - db:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  app:
    restart: on-failure
    depends_on:
      db:
        condition: service_healthy

    build: .
    ports:
      - 8080:8080
    env_file: ./.env
    environment:
      - spring.datasource.username=$DB_USER
      - spring.datasource.password=$DB_PASSWORD
      - spring.datasource.url=jdbc:mysql://db:$DB_PORT/role_based_authorization?&useSSL=false&allowPublicKeyRetrieval=true
      - spring.jpa.hibernate.ddl-auto=update

    networks:
      - this-api-net

volumes:
  db:
networks:
  this-api-net:
