spring:
  config:
    import: file:env.properties

  datasource:
    url: jdbc:mysql://localhost:3306/${DB}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format-sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect
    defer-datasource-initialization: true

  sql:
    init:
      mode: always

  jackson:
    default-property-inclusion: NON_NULL

  output:
    ansi:
      enabled: always

logging:
  level:
    root: INFO
    com:
      tuts: DEBUG

  pattern:
    console: |
      %clr(%d{HH:mm:ss.SSS}){green} %clr([%level]){magenta} %c{1.} [%t] %m%n
    file: |
      %clr(%d{yyyy-MM-dd HH:mm:ss.SSS}){green} [%level] %c{1.} [%t] %m%n

application:
  security:
    jwt:
      secret-key: ${JWT_SECRET}
      expiration: 120000 #two minutes
      refresh:
        expiration: 86400000 #one day
  jwt-expiration-milliseconds: 120000

  jwt-refresh-expiration-milliseconds: 7776000000
  db-stored-token-milliseconds: 60000
