apiVersion: apps/v1
kind: Deployment
metadata:
  name: role-based-auth
spec:
  selector:
    matchLabels:
      app: role-based-auth
  template:
    metadata:
      labels:
        app: role-based-auth
    spec:
      containers:
        - image: ywalakamar/role-based-auth:v1
          name: role-based-auth
          env:
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: db-conf
                  key: host
            - name: DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: db-conf
                  key: database
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: username
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: password

          resources:
            limits:
              memory: 1Gi
              cpu: 500m
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: role-based-auth
  labels:
    name: role-based-auth
spec:
  selector:
    app: role-based-auth
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30162
      protocol: TCP
